=== chatchatabc/parking-backend-spring/parking-domain/src/test/resources/db/datasets/database.dtd
<!ELEMENT dataset (
    authorities*,
    cloud_file*,
    coupon*,
    flyway_schema_history*,
    invoice*,
    jeepney*,
    jeepney_ride*,
    parking_lot*,
    parking_lot_image*,
    rate*,
    report*,
    report_status*,
    role*,
    route*,
    route_edge*,
    route_node*,
    user_activity_log*,
    user_ban_history_log*,
    user_login_log*,
    user_logout_log*,
    user_vehicle*,
    users*,
    vehicle*,
    vehicle_brand*,
    vehicle_model*,
    vehicle_type*)>

<!ELEMENT authorities EMPTY>
<!ATTLIST authorities
    username CDATA #REQUIRED
    authority CDATA #REQUIRED
>

<!ELEMENT cloud_file EMPTY>
<!ATTLIST cloud_file
    id CDATA #IMPLIED
    bucket CDATA #IMPLIED
    key CDATA #REQUIRED
    name CDATA #REQUIRED
    size CDATA #REQUIRED
    mime_type CDATA #REQUIRED
    tags CDATA #IMPLIED
    status CDATA #IMPLIED
    uploaded_by CDATA #REQUIRED
    created_at CDATA #REQUIRED
    updated_at CDATA #IMPLIED
>

<!ELEMENT coupon EMPTY>
<!ATTLIST coupon
    id CDATA #IMPLIED
    coupon_uuid CDATA #REQUIRED
    name CDATA #REQUIRED
    description CDATA #REQUIRED
    code CDATA #REQUIRED
    status CDATA #IMPLIED
    flag CDATA #IMPLIED
    valid_until CDATA #REQUIRED
    created_by CDATA #REQUIRED
    approved_by CDATA #IMPLIED
    created_at CDATA #REQUIRED
    updated_at CDATA #REQUIRED
>

<!ELEMENT flyway_schema_history EMPTY>
<!ATTLIST flyway_schema_history
    installed_rank CDATA #REQUIRED
    version CDATA #IMPLIED
    description CDATA #REQUIRED
    type CDATA #REQUIRED
    script CDATA #REQUIRED
    checksum CDATA #IMPLIED
    installed_by CDATA #REQUIRED
    installed_on CDATA #IMPLIED
    execution_time CDATA #REQUIRED
    success CDATA #REQUIRED
>

<!ELEMENT invoice EMPTY>
<!ATTLIST invoice
    id CDATA #IMPLIED
    invoice_uuid CDATA #REQUIRED
    parking_lot_uuid CDATA #REQUIRED
    vehicle_uuid CDATA #REQUIRED
    estimated_parking_duration_in_hours CDATA #IMPLIED
    estimated_end_at CDATA #IMPLIED
    total CDATA #IMPLIED
    paid_at CDATA #IMPLIED
    start_at CDATA #REQUIRED
    end_at CDATA #IMPLIED
    created_at CDATA #REQUIRED
    updated_at CDATA #REQUIRED
>

<!ELEMENT jeepney EMPTY>
<!ATTLIST jeepney
    id CDATA #IMPLIED
    jeepney_uuid CDATA #REQUIRED
    name CDATA #REQUIRED
    plate_number CDATA #REQUIRED
    current_ride_id CDATA #IMPLIED
    route_uuid CDATA #IMPLIED
    drivers CDATA #REQUIRED
    capacity CDATA #REQUIRED
    available_slots CDATA #REQUIRED
    latitude CDATA #REQUIRED
    longitude CDATA #REQUIRED
    status CDATA #IMPLIED
    flag CDATA #IMPLIED
    created_at CDATA #REQUIRED
    updated_at CDATA #REQUIRED
>

<!ELEMENT jeepney_ride EMPTY>
<!ATTLIST jeepney_ride
    id CDATA #IMPLIED
    jeepney_id CDATA #REQUIRED
    route_id CDATA #REQUIRED
    driver_id CDATA #REQUIRED
    start_at CDATA #IMPLIED
    end_at CDATA #IMPLIED
    status CDATA #IMPLIED
    flag CDATA #IMPLIED
    total_passengers CDATA #IMPLIED
    created_at CDATA #REQUIRED
    updated_at CDATA #REQUIRED
>

<!ELEMENT parking_lot EMPTY>
<!ATTLIST parking_lot
    id CDATA #IMPLIED
    parking_lot_uuid CDATA #REQUIRED
    owner_id CDATA #REQUIRED
    rate_id CDATA #IMPLIED
    name CDATA #REQUIRED
    address CDATA #REQUIRED
    latitude CDATA #REQUIRED
    longitude CDATA #REQUIRED
    description CDATA #IMPLIED
    capacity CDATA #IMPLIED
    available_slots CDATA #IMPLIED
    business_hours_start CDATA #REQUIRED
    business_hours_end CDATA #REQUIRED
    open_days_flag CDATA #IMPLIED
    flag CDATA #IMPLIED
    verified_at CDATA #IMPLIED
    verified_by CDATA #IMPLIED
    rejection_reason CDATA #IMPLIED
    status CDATA #IMPLIED
    created_at CDATA #REQUIRED
    updated_at CDATA #REQUIRED
>

<!ELEMENT parking_lot_image EMPTY>
<!ATTLIST parking_lot_image
    id CDATA #REQUIRED
    cloud_file_id CDATA #REQUIRED
    parking_lot_id CDATA #REQUIRED
    file_order CDATA #IMPLIED
>

<!ELEMENT rate EMPTY>
<!ATTLIST rate
    id CDATA #REQUIRED
    type CDATA #IMPLIED
    interval CDATA #IMPLIED
    free_hours CDATA #IMPLIED
    pay_for_free_hours_when_exceeding CDATA #IMPLIED
    starting_rate CDATA #IMPLIED
    rate CDATA #IMPLIED
    created_at CDATA #REQUIRED
    updated_at CDATA #REQUIRED
>

<!ELEMENT report EMPTY>
<!ATTLIST report
    id CDATA #IMPLIED
    name CDATA #REQUIRED
    description CDATA #REQUIRED
    plate_number CDATA #REQUIRED
    latitude CDATA #REQUIRED
    longitude CDATA #REQUIRED
    reported_by CDATA #REQUIRED
    cancelled_at CDATA #IMPLIED
    created_at CDATA #REQUIRED
    updated_at CDATA #REQUIRED
>

<!ELEMENT report_status EMPTY>
<!ATTLIST report_status
    id CDATA #IMPLIED
    report_id CDATA #REQUIRED
    performed_by CDATA #REQUIRED
    status CDATA #IMPLIED
    remarks CDATA #IMPLIED
    created_at CDATA #REQUIRED
>

<!ELEMENT role EMPTY>
<!ATTLIST role
    id CDATA #IMPLIED
    name CDATA #REQUIRED
>

<!ELEMENT route EMPTY>
<!ATTLIST route
    id CDATA #IMPLIED
    route_uuid CDATA #REQUIRED
    name CDATA #REQUIRED
    description CDATA #REQUIRED
    status CDATA #IMPLIED
    flag CDATA #IMPLIED
    created_at CDATA #REQUIRED
    updated_at CDATA #REQUIRED
>

<!ELEMENT route_edge EMPTY>
<!ATTLIST route_edge
    id CDATA #IMPLIED
    route_id CDATA #REQUIRED
    node_from CDATA #REQUIRED
    node_to CDATA #REQUIRED
    distance CDATA #REQUIRED
    created_at CDATA #REQUIRED
>

<!ELEMENT route_node EMPTY>
<!ATTLIST route_node
    id CDATA #IMPLIED
    latitude CDATA #REQUIRED
    longitude CDATA #REQUIRED
    poi CDATA #IMPLIED
    created_at CDATA #REQUIRED
>

<!ELEMENT user_activity_log EMPTY>
<!ATTLIST user_activity_log
    id CDATA #IMPLIED
    performed_by CDATA #REQUIRED
    name CDATA #IMPLIED
    target_id CDATA #IMPLIED
    event_type CDATA #IMPLIED
    column_name CDATA #IMPLIED
    data_before CDATA #IMPLIED
    data_after CDATA #IMPLIED
    created_at CDATA #REQUIRED
>

<!ELEMENT user_ban_history_log EMPTY>
<!ATTLIST user_ban_history_log
    id CDATA #IMPLIED
    user_id CDATA #REQUIRED
    banned_by CDATA #REQUIRED
    until CDATA #REQUIRED
    reason CDATA #IMPLIED
    unban_reason CDATA #IMPLIED
    unbanned_by CDATA #IMPLIED
    unbanned_at CDATA #IMPLIED
    status CDATA #IMPLIED
    created_at CDATA #REQUIRED
>

<!ELEMENT user_login_log EMPTY>
<!ATTLIST user_login_log
    id CDATA #IMPLIED
    user_id CDATA #REQUIRED
    type CDATA #IMPLIED
    ip_address CDATA #REQUIRED
    success CDATA #IMPLIED
    created_at CDATA #REQUIRED
>

<!ELEMENT user_logout_log EMPTY>
<!ATTLIST user_logout_log
    id CDATA #IMPLIED
    user_id CDATA #REQUIRED
    type CDATA #IMPLIED
    ip_address CDATA #REQUIRED
    created_at CDATA #REQUIRED
>

<!ELEMENT user_vehicle EMPTY>
<!ATTLIST user_vehicle
    user_id CDATA #REQUIRED
    vehicle_id CDATA #REQUIRED
>

<!ELEMENT users EMPTY>
<!ATTLIST users
    id CDATA #IMPLIED
    user_uuid CDATA #REQUIRED
    notification_uuid CDATA #REQUIRED
    email CDATA #IMPLIED
    username CDATA #IMPLIED
    password CDATA #IMPLIED
    phone CDATA #REQUIRED
    first_name CDATA #IMPLIED
    last_name CDATA #IMPLIED
    avatar CDATA #IMPLIED
    flag CDATA #IMPLIED
    status CDATA #IMPLIED
    enabled CDATA #IMPLIED
    email_verified_at CDATA #IMPLIED
    phone_verified_at CDATA #IMPLIED
    created_at CDATA #REQUIRED
    updated_at CDATA #REQUIRED
>

<!ELEMENT vehicle EMPTY>
<!ATTLIST vehicle
    id CDATA #IMPLIED
    vehicle_uuid CDATA #REQUIRED
    name CDATA #REQUIRED
    plate_number CDATA #REQUIRED
    brand_uuid CDATA #REQUIRED
    model_uuid CDATA #REQUIRED
    type_uuid CDATA #REQUIRED
    color CDATA #IMPLIED
    year CDATA #IMPLIED
    owner_id CDATA #REQUIRED
    created_at CDATA #REQUIRED
    updated_at CDATA #REQUIRED
>

<!ELEMENT vehicle_brand EMPTY>
<!ATTLIST vehicle_brand
    id CDATA #IMPLIED
    brand_uuid CDATA #REQUIRED
    name CDATA #REQUIRED
    status CDATA #IMPLIED
    created_by CDATA #REQUIRED
    created_at CDATA #REQUIRED
    updated_at CDATA #REQUIRED
>

<!ELEMENT vehicle_model EMPTY>
<!ATTLIST vehicle_model
    id CDATA #IMPLIED
    model_uuid CDATA #REQUIRED
    brand_uuid CDATA #REQUIRED
    name CDATA #REQUIRED
    status CDATA #IMPLIED
    created_by CDATA #REQUIRED
    created_at CDATA #REQUIRED
    updated_at CDATA #REQUIRED
>

<!ELEMENT vehicle_type EMPTY>
<!ATTLIST vehicle_type
    id CDATA #IMPLIED
    type_uuid CDATA #REQUIRED
    name CDATA #REQUIRED
    status CDATA #IMPLIED
    created_by CDATA #REQUIRED
    created_at CDATA #REQUIRED
    updated_at CDATA #REQUIRED
>

=== chatchatabc/parking-backend-spring/parking-domain/src/test/resources/db/datasets/route_node.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset SYSTEM "database.dtd">

<dataset>
    <route_node id="1" latitude="7.109815773766583" longitude="125.63233674148502"
                created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="2" latitude="7.1098137999999995" longitude="125.63231180000001"
                created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="3" latitude="7.109215100000001" longitude="125.63234209999999"
                created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="4" latitude="7.1085999" longitude="125.63238369999999" created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="5" latitude="7.1081077" longitude="125.6324129" created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="6" latitude="7.107831499999999" longitude="125.6324389" created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="7" latitude="7.1074545" longitude="125.63246669999998" created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="8" latitude="7.1064978" longitude="125.6325274" created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="9" latitude="7.106537899999999" longitude="125.6329105" created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="10" latitude="7.1065776" longitude="125.63318899999999" created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="11" latitude="7.106617563095244" longitude="125.63334300695739"
                created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="12" latitude="7.1066446" longitude="125.63344719999998" created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="13" latitude="7.1072699" longitude="125.6346553" created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="14" latitude="7.107508532199416" longitude="125.63510068075436"
                created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="15" latitude="7.1075108999999985" longitude="125.6351051" created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="16" latitude="7.1081088999999995" longitude="125.6351265" created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="17" latitude="7.108833" longitude="125.63504710000001" created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="18" latitude="7.109130399999999" longitude="125.63500479999999"
                created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="19" latitude="7.109522" longitude="125.63495789999999" created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="20" latitude="7.1098618" longitude="125.6349311" created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="21" latitude="7.1098688999999995" longitude="125.63419509999999"
                created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="22" latitude="7.1098716999999985" longitude="125.63370540000001"
                created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="23" latitude="7.109868099999999" longitude="125.633218" created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="24" latitude="7.1098559" longitude="125.6328438" created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="25" latitude="7.107381569297203" longitude="125.63511082633812"
                created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="26" latitude="7.105909628131386" longitude="125.63484148360908"
                created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="27" latitude="7.106370578634923" longitude="125.63295608451728"
                created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="28" latitude="7.1061575343416195" longitude="125.6338343760197"
                created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="29" latitude="7.107381569297203" longitude="125.63511082633812"
                created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="30" latitude="7.105909628131386" longitude="125.63484148360908"
                created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="31" latitude="7.106370578634923" longitude="125.63295608451728"
                created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="32" latitude="7.1061575343416195" longitude="125.6338343760197"
                created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="33" latitude="7.106019370797085" longitude="125.63258287298623"
                created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="34" latitude="7.104552225649741" longitude="125.63267886757359"
                created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="35" latitude="7.103776834353511" longitude="125.63271525396232"
                created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="36" latitude="7.105421081233786" longitude="125.63262600720878"
                created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="37" latitude="7.1030202180254065" longitude="125.63277313950641"
                created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="38" latitude="7.102501175865527" longitude="125.6328231709582"
                created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="39" latitude="7.102591563531234" longitude="125.63308242487273"
                created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="40" latitude="7.103345302665417" longitude="125.6330232967909"
                created_at="2023-05-10 16:14:47.307160"/>
    <route_node id="41" latitude="7.103358842878407" longitude="125.63275494627356"
                created_at="2023-05-10 16:14:47.307160"/>
</dataset>
